services:

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: my-ros-base:latest  

  drl:
    build:
      context: .
      dockerfile: Dockerfile.drl
    container_name: drl
    hostname: drl_container
    depends_on:
      - base
      - SERVICE_PLACEHOLDER
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://SERVICE_PLACEHOLDER:11311
      - ROS_HOSTNAME=drl
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../local_env/plots/drl:/app/plots
      - ../data/models:/app/models
      - ../data/gym_env:/app/gym_env
      - ./drl_code:/app/drl_code
    command: >
      bash -c '
      rm -rf /app/drl_code/milliAmpere1ROS_env && 
      cp -r /app/gym_env/milliAmpere1ROS_env /app/drl_code/ && 
      source /opt/ros/noetic/setup.bash && 
      tail -f /dev/null
      '
    networks:
      - ros_net
    devices:
      - /dev/dri:/dev/dri  # Required for hardware acceleration (optional)
    init: true  # Add this line
  
  xai:
    build:
      context: .
      dockerfile: Dockerfile.xai
    container_name: xai
    hostname: xai_contatiner
    depends_on:
      - base
      - SERVICE_PLACEHOLDER
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_MASTER_URI=http://SERVICE_PLACEHOLDER:11311
      - ROS_HOSTNAME=xai
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../local_env/plots/xai:/app/plots
      - ../data/models:/app/models
      - ../data/gym_env:/app/gym_env
      - ./xai_code:/app/xai_code
    command: >
      bash -c '
      rm -rf /app/xai_code/milliAmpere1ROS_env && 
      cp -r /app/gym_env/milliAmpere1ROS_env /app/xai_code/ && 
      source /opt/ros/noetic/setup.bash && 
      tail -f /dev/null
      '
    networks:
      - ros_net
    devices:
      - /dev/dri:/dev/dri  # Required for hardware acceleration (optional)
    init: true  # Add this line

  simulator:
    build: ./milliAmpere1_code
    container_name: simulator
    hostname: simulator_container
    environment:
      DISPLAY: ${DISPLAY}
      LD_LIBRARY_PATH: "/workspace/src/ma27"
      ROS_LANG_DISABLE: 'genlisp;gennodejs;geneus'
      ROS_LOG_DIR: '/logging/node_logs'
      ROS_MASTER_URI: http://simulator:11311
      ROS_HOSTNAME: simulator
      CATKIN_ENABLE_TESTING: '0'
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    command: >
      bash -c "
      source /opt/ros/noetic/setup.bash &&
      roscore &
      sleep 3 &&
      source /workspace/devel/setup.bash &&
      roslaunch /workspace/src/simulator.launch &
      tail -f /dev/null
      "
    volumes:
      - "./milliAmpere1_code/workspace:/workspace:rw"
      - "./milliAmpere1_code/logging:/logging:rw"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${HOME}/.Xauthority:/root/.Xauthority:rw"
    ports:
      - "80"
      - "2020"
      - "2030"
      - "61200:61200"
    stdin_open: true
    tty: true
    networks:
      - ros_net

  real_vessel:
    build: 
      context: ./milliAmpere1_code
      args:
        USERNAME: ma
        USER_UID: 1000
        USER_GID: 1000
      dockerfile: Dockerfile
    container_name: real_vessel
    hostname: real_vessel_container
    environment:
      DISPLAY: ${DISPLAY}
      LD_LIBRARY_PATH: "/workspace/src/ma27"
      ROS_LANG_DISABLE: 'genlisp;genjava;gennodejs;geneus'
      ROS_LOG_DIR: /logging/node_logs
      ROS_MASTER_URI: http://real_vessel:11311
      ROS_HOSTNAME: real_vessel
      XAUTHORITY: '/tmp/.docker.xauth'
      PYTHONDONTWRITEBYTECODE: 1
      CATKIN_ENABLE_TESTING: 0
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - "./milliAmpere1_code/workspace:/workspace:rw"
      - "./milliAmpere1_code/logging:/logging:rw"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${HOME}/.Xauthority:/root/.Xauthority:rw"
      - "/home/${USER}:/home/${USER}:rw"
      - "/tmp/.docker.xauth:/tmp/.docker.xauth"
    devices:
      - "/dev/arduino_RC:/dev/arduino_RC"
      - "/dev/xSens:/dev/xSens"
      - "/dev/vector_vs330:/dev/vector_vs330"
      - "/dev/ttyUSB0:/dev/ttyUSB0"   #IMU
      #- "/dev/ttyACM0:/dev/ttyACM0"   #Arduino (RM)
      - "/dev/ttyS0:/dev/ttyS0"       # GPS
      - "/dev/ttyS1:/dev/ttyS1"       # GPS
      - "/dev/ttyS2:/dev/ttyS2"       # GPS
      - "/dev/ttyS3:/dev/ttyS3"       # GPS
      - "/dev/ttyS4:/dev/ttyS4"       # GPS
    stdin_open: true
    tty: true
    networks:
      - ros_net
    cap_add:
      - NET_ADMIN
  
networks:
  ros_net:
    driver: bridge