# Dockerfile.drl
FROM my-ros-base:latest

# Install smach BEFORE building packages that depend on it
RUN apt-get update && apt-get install -y ros-noetic-smach

# Now copy the supervisor package
WORKDIR /root/catkin_ws/src
COPY milliAmpere1_code/workspace/src/supervisor ./supervisor

# Rebuild with the additional package
WORKDIR /root/catkin_ws
RUN /bin/bash -c "source /opt/ros/noetic/setup.bash && catkin_make"

WORKDIR /app/drl_code

# Copy just requirements first to leverage caching
COPY ./drl_code/requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

# Then copy your code
COPY ./drl_code/ .

# WORKDIR /app/gym_env
# RUN pip install -e ./milliAmpere1ROS_env

# WORKDIR /app/drl_code

CMD ["tail", "-f", "/dev/null"]