services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: my-ros-base:latest
  drl:
    build:
      context: .
      dockerfile: Dockerfile.drl
    container_name: drl
    hostname: drl_container
    depends_on:
    - base
    - simulator_local
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - ROS_MASTER_URI=http://simulator_local:11311
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
    - ${HOME}/.Xauthority:/root/.Xauthority:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ../local_env/plots/drl:/app/plots:rw
    - ../data/models:/app/models:rw
    - ../data/gym_env:/app/gym_env:rw
    - ../data/samples:/app/samples:rw
    - ./drl_code:/app/drl_code:rw
    command: 'bash -c '' rm -rf /app/drl_code/milliAmpere1ROS_env && cp -r /app/gym_env/milliAmpere1ROS_env /app/drl_code/ && source /opt/ros/noetic/setup.bash && tail -f /dev/null ''

      '
    networks:
    - ros_local_net
    devices:
    - /dev/dri:/dev/dri
    init: true
  xai:
    build:
      context: .
      dockerfile: Dockerfile.xai
    container_name: xai
    hostname: xai_container
    depends_on:
    - base
    - simulator_local
    environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - ROS_MASTER_URI=http://simulator_local:11311
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
    - ${HOME}/.Xauthority:/root/.Xauthority:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ../local_env/plots/xai:/app/plots:rw
    - ../data/models:/app/models:rw
    - ../data/gym_env:/app/gym_env:rw
    - ../data/samples:/app/samples:rw
    - ./xai_code:/app/xai_code:rw
    command: 'bash -c '' rm -rf /app/xai_code/milliAmpere1ROS_env && cp -r /app/gym_env/milliAmpere1ROS_env /app/xai_code/ && source /opt/ros/noetic/setup.bash && tail -f /dev/null ''

      '
    networks:
    - ros_local_net
    devices:
    - /dev/dri:/dev/dri
    init: true
  simulator_local:
    build: ./milliAmpere1_code
    container_name: simulator_local
    hostname: simulator_local_container
    environment:
    - DISPLAY=${DISPLAY}
    - LD_LIBRARY_PATH=/workspace/src/ma27
    - ROS_LANG_DISABLE=genlisp;gennodejs;geneus
    - ROS_LOG_DIR=/logging/node_logs
    - ROS_MASTER_URI=http://simulator_local:11311
    - CATKIN_ENABLE_TESTING='0'
    - QT_X11_NO_MITSHM=1
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    command: 'bash -c '' source /opt/ros/noetic/setup.bash && roscore & sleep 5 && source /workspace/devel/setup.bash && roslaunch /workspace/src/simulator.launch & tail -f /dev/null ''

      '
    volumes:
    - ./milliAmpere1_code/workspace:/workspace:rw
    - ./milliAmpere1_code/logging:/logging:rw
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ${HOME}/.Xauthority:/root/.Xauthority:rw
    ports:
    - '80'
    - '2020'
    - '2030'
    - 61200:61200
    - 11311:11311
    stdin_open: true
    tty: true
    networks:
    - ros_local_net
networks:
  ros_local_net:
    driver: bridge
