repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: "^(data/|xai/src/milliampere_xai/dashboard\\.py)"
      - id: ruff-format
        exclude: "^(data/|xai/src/milliampere_xai/dashboard\\.py)"

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]
