repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check
        args: [--fix]
        exclude: "^(data/|local_env/)"
      - id: ruff-format
        exclude: "^(data/|local_env/)"
