<?xml version="1.0"?>
<package format="2">
  <name>milliampere_env</name>
  <version>0.1.0</version>
  <description>Consolidated gymnasium environment for milliAmpere1 dynamic positioning.</description>
  <maintainer email="alexander@sandberg-oslo.no">Alexander Sandberg</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <exec_depend>rospy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>custom_ros_msgs</exec_depend>
</package>
