services:
  ros_master:
    image: ros:noetic-ros-core
    container_name: ros_master
    hostname: ros_master_container
    networks:
      rosnet:
        aliases:
          - ros_master
    command: roscore

  simulator:
    build:
      context: ./milliampere_code
    container_name: simulator
    hostname: simulator_container
    depends_on:
      - ros_master
    networks:
      rosnet:
        aliases:
          - simulator
    environment:
      DISPLAY: ${DISPLAY}
      LD_LIBRARY_PATH: "/workspace/src/ma27"
      ROS_LANG_DISABLE: 'genlisp;gennodejs;geneus'
      ROS_LOG_DIR: '/logging/node_logs'
      ROS_MASTER_URI: http://ros_master:11311
      ROS_HOSTNAME: simulator
      CATKIN_ENABLE_TESTING: '0'
      QT_X11_NO_MITSHM: 1
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    volumes:
      - "./milliampere_code/workspace/src:/workspace/src:rw"  # Mount only the src directory
    #  - "./milliampere_code/workspace:/workspace:rw"
      - "./milliampere_code/logging:/logging:rw"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "${HOME}/.Xauthority:/root/.Xauthority:rw"
    ports:
      - "80:80"
      - "2020:2020"
      - "2030:2030"
      - "61200:61200"
    stdin_open: true
    tty: true

  rl_agent:
    build:
      context: .
      dockerfile: Dockerfile.rl
    container_name: rl_agent
    hostname: rl_container
    depends_on:
      - simulator
    networks:
      rosnet:
        aliases:
          - rl_agent
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://ros_master:11311
      - ROS_HOSTNAME=rl_agent
      - QT_X11_NO_MITSHM=1
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./rl_code:/app/rl_code
      - ./models:/app/models
      - ./logs:/app/logs
    devices:
      - /dev/dri:/dev/dri  # Required for hardware acceleration (optional)
    init: true  # Add this line


  xai_agent:
    build:
      context: .
      dockerfile: Dockerfile.xai
    container_name: xai_agent
    hostname: xai_container
    depends_on:
      - simulator
    networks:
      rosnet:
        aliases:
          - xai_agent
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://ros_master:11311
      - ROS_HOSTNAME=xai_agent
      - QT_X11_NO_MITSHM=1
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./xai_code:/app/xai_code
      - ./models:/app/models
      - ./logs:/app/logs
    devices:
      - /dev/dri:/dev/dri  # Required for hardware acceleration (optional)
    init: true  # Add this line


networks:
  rosnet:
